CREATE VIEW weekly_amounts AS
SELECT 
    category,
    amount_per_week AS W13,
    amount_per_week AS W14,
    amount_per_week AS W15,
    amount_per_week AS W16,
    amount_per_week AS W17,
    amount_per_week AS W18,
    amount_per_week AS W19,
    amount_per_week AS W20,
    amount_per_week AS W21,
    amount_per_week AS W22,
    amount_per_week AS W23,
    amount_per_week AS W24,
    amount_per_week AS W25,
      amount_per_week AS W26
FROM customers_Target_data;
