CREATE VIEW weekly_amounts AS
SELECT 
    category,
    amount_per_week AS 2025-13,
    amount_per_week AS 2025-14,
    amount_per_week AS 2025-15,
    amount_per_week AS 2025-16,
    amount_per_week AS 2025-17,
    amount_per_week AS 2025-18,
    amount_per_week AS 2025-19,
    amount_per_week AS 2025-20,
    amount_per_week AS 2025-21,
    amount_per_week AS 2025-22,
    amount_per_week AS 2025-23,
    amount_per_week AS 2025-24,
    amount_per_week AS 2025-25,
    amount_per_week AS 2025-26
FROM customers_Target_data;
